config/routes.rb
Rails.application.routes.draw do

  root 'welcome#welcome'
  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  get '/login', to: 'authentications#new'
  post '/login', to: 'authentications#create'
  delete '/logout', to: 'authentications#destroy'
  get '/feed', to: 'feed#feed'
  get 'users/:id/follow', to: 'relationships#index', as: "follow"

  resources :users, only: [:index, :show]
  resources :posts, only: [:index, :new, :create, :show, :edit, :update]
  resources :trips, only: [:index, :new, :create, :show, :edit, :update]
  resources :comments, only: [:create]
  resources :relationships, only: [:create, :destroy]

  delete 'trips/:id', to: 'trips#destroy'
  delete 'posts/:id', to: 'posts#destroy'

end

app/models/trip.rb
class Trip < ApplicationRecord

  belongs_to :user
  has_many :comments, as: :commentable

  validates :title, :rating, :content, :date, :region, presence: true

  def author
    trip_owner = User.find(self.user_id)
    "#{trip_owner.first_name} #{trip_owner.last_name}"
  end

end

app/controllers/trips_controller.rb
class TripsController < ApplicationController

  before_action :redirect_if_not_logged_in

  def index
    @trips = Trip.all.reverse
  end

  def show
    @user = User.find(session[:user_id])
    @trip = Trip.find(params[:id])
    @follow = @trip.user
    @event_user_id = @follow.id
    @comment = Comment.new(commentable: @trip)
    @comments = Comment.trip_comments.select {|comment| comment.commentable_id == params[:id].to_i}
  end

  def new
    @trip = Trip.new
    @errors = @trip.errors
  end

  def create
    @trip = Trip.new(trip_params)
    @trip.user_id = session[:user_id]
    if @trip.save
      redirect_to @trip
    else
      @errors = @trip.errors.full_messages
      render :new
    end
  end

  def edit
    @trip = Trip.find(params[:id])
  end

  def update
    @trip = Trip.find(params[:id])
    @trip.update(title: trip_params['title'], rating: trip_params['rating'], content: trip_params['content'], region: trip_params['region'])
    redirect_to trip_path(@trip)
  end

  def destroy
    @trip = Trip.find(params[:id])
    @trip.destroy
    redirect_to feed_path
  end


private

  def trip_params
    params.require(:trip).permit(:title, :rating, :content, :date, :region)
  end

end

app/helpers/trips_helper.rb
module TripsHelper
end

app/views/trips/edit.erb
<div class='font'>
<div class='form'>
<h2>Edit Trip</h2>
<%=form_for @trip do |f|%>
<%=f.label :title%>
<%=f.text_field :title%><br><br>
<%=f.label :rating%>
<%=f.number_field :rating, step: 0.25%><br><br>
<%=f.label :date%>
<%=f.date_field :date%><br><br>
<%=f.label :region%>
<%=f.select :region, [['North Cascades', 'north cascades'],['Central Cascades', 'central cascades'],['Mount Ranier','mount rainier'],['Wenatchee National Forest','wenatchee national forest'],['Mount Baker-Snoqualmie National Forest', 'mount baker-snoqualmie national forest'],['Colville National Forest','colville national forest'],['Olympic Penninsula','olympic penninsula'],['Eastern Washington', 'eastern washington'],['Issaquah Alps', 'issaquah alps'],['Pudget Sound', 'pudget sound'],['South Cascades', 'south cascades'],['Seattle Area', 'aeattle area']]%><br><br>
<%=f.label :content%>
<%=f.text_area :content%><br>
<%=f.submit%>
<%end%>

</div>
</div>

app/views/trips/index.erb
<div class='background'>
<div class='font'>
<text class='posts_index'> Trips </text><br><br><br><br><br>
<% @trips.each do |trip| %>
<div class='feed_words'><%= link_to "#{trip.title}", trip%></div><br>
<text style="font-size:30px"><%=trip.region%></text>
<div class='post_details'><%= "(#{trip.rating}) - #{trip.content}..."%></div>
<br><br><br><br><br><br>
<% end %>
</div>
</div>

app/views/trips/new.erb
<div class='font'>
<div class='form'>
<h2>New Trip</h2>
<%@errors.each do |error|%>
<h3><%=error%></h3>
<%end%>
<%=form_for @trip do |f|%>
<%=f.label :title%>
<%=f.text_field :title%><br><br>
<%=f.label :rating%>
<%=f.number_field :rating, step: 0.25%><br><br>
<%=f.label :date%>
<%=f.date_field :date%><br><br>
<%=f.label :region%>
<%=f.select :region, [['North Cascades', 'north cascades'],['Central Cascades', 'central cascades'],['Mount Ranier','mount rainier'],['Wenatchee National Forest','wenatchee national forest'],['Mount Baker-Snoqualmie National Forest', 'mount baker-snoqualmie national forest'],['Colville National Forest','colville national forest'],['Olympic Penninsula','olympic penninsula'],['Eastern Washington', 'eastern washington'],['Issaquah Alps', 'issaquah alps'],['Pudget Sound', 'pudget sound'],['South Cascades', 'south cascades'],['Seattle Area', 'aeattle area']]%><br><br>
<%=f.label :content%>
<%=f.text_area :content%><br>
<%=f.submit%>
<%end%>

</div>
</div>

app/views/trips/show.erb
<div class='backgroundbox'>
<div class='font'>
  <h1><%=@trip.title%></h1>
    <p>By: <%=link_to @trip.user.username, user_path(@trip.user)%></p>
    <%= render 'relationships/follow', locals: {follow: @follow, user: @user} %><br>
    <text>---------------------------------</text>
    <p><strong>Region: </strong><%=@trip.region%>  -  <strong>Rating: </strong><%=@trip.rating%>  -  <strong>Date of Trip: </strong><%=@trip.date%></p>
    <text>---------------------------------</text>
    <p><%=@trip.content%></p><br>

  <text>---------------------------------</text>
  <text>COMMENTS</text>
  <text>---------------------------------</text>

  <%@comments.reverse.each do |comment|%>
    <p class='comment'><%=comment.content%></p>
    <p class='comment_author'>@<%=User.find(comment.user_id).username%></p>
    <text>---------------------------------</text>
  <%end%>

  <%= render partial: 'comments/form', object: @comment  %>
<br>
<br>
<% if session[:user_id] == @trip.user_id%>
<text style='margin-right: 50px;'><%= link_to "Update Trip", edit_trip_path(@trip) %></text>
<%= link_to "Delete Trip", @trip, method: :delete, data: { confirm: "Are you sure?" } %>
<%end%><br><br><br>
</div>
</div>