config/routes.rb
Rails.application.routes.draw do

  root 'welcome#welcome'
  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  get '/login', to: 'authentications#new'
  post '/login', to: 'authentications#create'
  delete '/logout', to: 'authentications#destroy'
  get '/feed', to: 'feed#feed'
  get 'users/:id/follow', to: 'relationships#index', as: "follow"

  resources :users, only: [:index, :show]
  resources :posts, only: [:index, :new, :create, :show, :edit, :update]
  resources :trips, only: [:index, :new, :create, :show, :edit, :update]
  resources :comments, only: [:create]
  resources :relationships, only: [:create, :destroy]

  delete 'trips/:id', to: 'trips#destroy'
  delete 'posts/:id', to: 'posts#destroy'

end

app/models/relationship.rb
class Relationship < ApplicationRecord

  belongs_to :followed_user, class_name: "User", foreign_key: :followed_id
  belongs_to :follower_user, class_name: "User", foreign_key: :follower_id




end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController

  def index
    @user = User.find(params[:id])
    @following_relationships = @user.active_relationships
    @follower_relationships = @user.passive_relationships
    @followingcount = @following_relationships.count
    @followercount = @follower_relationships.count
    @followingobjects = @following_relationships.map do |ar|
      User.find(ar.followed_id)
    end
    @followerobjects = @follower_relationships.map do |pr|
      User.find(pr.follower_id)
    end

  end

  def create
    Relationship.create(follower_id: params[:follower_id], followed_id: params[:followed_id])
    redirect_back(fallback_location: root_path)
  end


  def destroy
    @user = User.find(session[:user_id])
    @followed_id = get_id(params)
    @relation = Relationship.find do |r| r.follower_id == @user.id && r.followed_id == @followed_id
    end
    @relation.destroy
    redirect_back(fallback_location: root_path)
  end


  private

  def get_id(params)
    if params[:page_type] == 'users'
      User.find(params[:id]).id
    elsif params[:page_type] == 'trips'
      Trip.find(params[:id]).user_id
    else
      Post.find(params[:id]).user_id
    end
  end


end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/views/relationships/_follow.html.erb
<% if @event_user_id != session[:user_id] %>
  <% if !@user.follow?(@follow) %>
    <%= form_tag('/relationships') do %>
      <%= hidden_field_tag :followed_id, @follow.id %>
      <%= hidden_field_tag :follower_id, @user.id %>
      <%= submit_tag "Follow" %>
    <% end %>

  <% else %>

    <%= button_to "Unfollow", relationship_path, method: :delete, params: {page_type: params[:controller]} %>

  <% end %>

<% end %>

app/views/relationships/index.html.erb
<div class='backgroundbox'>
<div class='font'>
  <h3><%= "Following (#{@followingcount})" %></h3>
  <% @followingobjects.each do |ar| %>
  <%= link_to ar.username, user_path(ar) %><br>
  <% end %>
  <br>
  <br>
  <h3><%= "Followers (#{@followercount})" %></h3>
  <% @followerobjects.each do |pr| %>
  <%= link_to pr.username, user_path(pr) %><br><br><br>
  <% end %>
</div>
</div>