config/routes.rb
Rails.application.routes.draw do

  root 'welcome#welcome'
  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  get '/login', to: 'authentications#new'
  post '/login', to: 'authentications#create'
  delete '/logout', to: 'authentications#destroy'
  get '/feed', to: 'feed#feed'
  get 'users/:id/follow', to: 'relationships#index', as: "follow"

  resources :users, only: [:index, :show]
  resources :posts, only: [:index, :new, :create, :show, :edit, :update]
  resources :trips, only: [:index, :new, :create, :show, :edit, :update]
  resources :comments, only: [:create]
  resources :relationships, only: [:create, :destroy]

  delete 'trips/:id', to: 'trips#destroy'
  delete 'posts/:id', to: 'posts#destroy'

end

app/models/user.rb
class User < ApplicationRecord

  has_secure_password

  validates :first_name, :last_name, :username, :password, :password_confirmation, presence: true
  validates :username, uniqueness: true

  has_many :trips
  has_many :posts

  has_many :comments

  has_many :active_relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :passive_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy

  has_many :followed_users, through: :active_relationships, source: :followed_user
  has_many :follower_users, through: :passive_relationships, source: :follower_user


  def follow?(follow)
    followed_users.include?(follow)
  end

  def full_name
    "#{self.first_name} #{self.last_name}"

  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :redirect_if_not_logged_in, except: [:new,:create]

  def index
    @users = User.all
  end

  def show
    @user = User.find(session[:user_id])
    @follow = User.find(params[:id])
    @event_user_id = @follow.id
    @following_relationships = @follow.active_relationships
    @follower_relationships = @follow.passive_relationships

    current_user = User.find(params[:id])

    @followingcount = @following_relationships.count
    @followercount = @follower_relationships.count

    @followingobjects = @following_relationships.map do |ar|
      User.find(ar.followed_id)
    end

    @followerobjects = @follower_relationships.map do |pr|
      User.find(pr.follower_id)
    end

    @posts = @follow.posts.last(5)
    @trips = @follow.trips.last(5)
  end



  def new
    @user = User.new
  end



  def create
    @user = User.new(user_params)
    if @user.valid?
      @user.save
      redirect_to '/feed'
    else
      @errors = @user.errors.full_messages
      render '/users/new'
    end
  end




  private
    def user_params
      params.require(:user).permit(:first_name, :last_name, :username, :password_confirmation, :password)
    end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/index.erb
<div class='backgroundbox'>
  <% @users.each do |user| %>
  <%= link_to "#{user.first_name} #{user.last_name}", user%><br>
  <%end %>
<div>

app/views/users/new.html.erb
<% if @user.errors.any? %>
  <h4 class="error_explanation">
    <% @errors.each do |msg| %>
    <%= msg %><br>
    <% end %>
  </h4>
<% end %>


<div class = 'trip_post_text'>
<div class = 'font'>

  <body>

    <div class='login'>

        <%= form_for :user, url: '/signup' do |f| %>
          <p><%=f.label :first_name%>
          <%=f.text_field :first_name%></p>
          <p><%=f.label :last_name%>
          <%=f.text_field :last_name%></p>
          <p><%=f.label :username%>
          <%=f.text_field :username%></p>
          <p><%=f.label :password%>
          <%=f.password_field :password%></p>
          <p><%=f.label "Confirm Password"%>
          <%=f.password_field :password_confirmation%></p>
          <p><%=f.submit "Create"%></p>
        <%end%>

        <p>Already have an account? <%=link_to "Sign In", login_path%></p>

    </div>

  </body>

</div>
</div>

app/views/users/show.erb
<div class='backgroundbox'>
<div class='font'>
<h1>@<%=@follow.username%></h1>

<text>Following <%= link_to "(#{@followingcount})", follow_path(@follow) %> ---
<text>Followers <%= link_to "(#{@followercount})", follow_path(@follow) %></text>
<%= render 'relationships/follow', locals: {follow: @follow, user: @user} %>

<h1><%= "Latest Trips" %></h1>
  <% @trips.each do |t| %>
  <text>---------------------------------</text>
      <h3><%= t.title %> - <%= "Rating: " + "#{t.rating}" %></h3> <%=link_to "Read the Full Trip", trip_path(t)%><br><br>
  <% end %>
  <br>
<h1><%= "Latest Posts" %></h1>
  <% @posts.each do |p| %>
  <text>---------------------------------</text>
      <h3><%= p.title %></h3>
      <%= p.description.truncate_words(4) %><br>
      <%=link_to "Read the Full Post", post_path(p)%>
  <% end %>
  <br>
  <br>
</div>
</div>