config/routes.rb
Rails.application.routes.draw do

  root 'welcome#welcome'
  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  get '/login', to: 'authentications#new'
  post '/login', to: 'authentications#create'
  delete '/logout', to: 'authentications#destroy'
  get '/feed', to: 'feed#feed'
  get 'users/:id/follow', to: 'relationships#index', as: "follow"

  resources :users, only: [:index, :show]
  resources :posts, only: [:index, :new, :create, :show, :edit, :update]
  resources :trips, only: [:index, :new, :create, :show, :edit, :update]
  resources :comments, only: [:create]
  resources :relationships, only: [:create, :destroy]

  delete 'trips/:id', to: 'trips#destroy'
  delete 'posts/:id', to: 'posts#destroy'

end

app/models/post.rb
class Post < ApplicationRecord

  belongs_to :user
  has_many :comments, as: :commentable

  validates :title, :description, presence: true

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  before_action :redirect_if_not_logged_in

  def index
    @posts = Post.all.reverse
  end

  def show
    @post = Post.find(params[:id])
    @user = User.find(session[:user_id])
    @follow = @post.user
    @event_user_id = @follow.id
    @comment = Comment.new(commentable: @post)
    @comments = Comment.post_comments.select {|comment| comment.commentable_id == params[:id].to_i}

  end

  def new
    @post = Post.new
    @errors = @post.errors
  end

  def create
    @post = Post.new(post_params)
    @post.user_id = session[:user_id]
      if @post.save
        redirect_to @post
      else
        @errors = @post.errors.full_messages
        render :new
      end

    end

    def edit
      @post = Post.find(params[:id])
    end

    def update
      @post = Post.find(params[:id])
      @post.update(title: post_params['title'], description: post_params['description'])
      redirect_to post_path(@post)
    end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to feed_path
  end



private

  def post_params
    params.require(:post).permit(:title, :description)
  end

end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/edit.erb
<div class='font'>
<div class='form'>
<h1>New Post</h1>
<%=form_for @post do |f|%>
<%=f.label :title%>
<%=f.text_field :title%><br><br>
<%=f.label :description%>
<%=f.text_area :description%>
<%=f.submit%>
<%end%>
</div>
</div>

app/views/posts/index.erb
<div class='background'>
<div class='font'>
  <text class='posts_index'> Posts </text><br><br>
  <% @posts.each do |post| %>
  <div style="text-decoration: none;", class="post_title"><%= link_to "#{post.title}", post%><br></div>
  <div class="post_details;"><%="#{post.description[0..30]}..."%><br></div>
  <br><br>
  <%end %>
</div>

app/views/posts/new.erb
<div class='font'>
<div class='form'>
<h1>New Post</h1>
<%@errors.each do |error|%>
<h3><%=error%></h3>
<%end%>
<%=form_for @post do |f|%>
<%=f.label :title%>
<%=f.text_field :title%><br><br>
<%=f.label :description%>
<%=f.text_area :description%>
<%=f.submit%>
<%end%>
</div>
</div>

app/views/posts/show.erb
<div class='backgroundbox'>
  <div class='font'>
  <h1><%=@post.title%></h1>
      <p>By: <%=link_to @post.user.username, user_path(@post.user)%></p>
      <%= render 'relationships/follow', locals: {follow: @follow, user: @user} %>
      <text>---------------------------------</text>
      <text>---------------------------------</text>
      <p><%=@post.description%></p><br>

      <text>---------------------------------</text>
      <text>COMMENTS</text>
      <text>---------------------------------</text>
      <%@comments.reverse.each do |comment|%>
        <p class='comment'><%=comment.content%></p>
        <p class='comment_author'>@<%=User.find(comment.user_id).username%></p>
        <text>---------------------------------</text>
      <%end%>

<%= render partial: 'comments/form', object: @comment  %>
<br>
<br>
<% if session[:user_id] == @post.user_id%>
<text style='margin-right: 50px;'><%= link_to "Update Trip", edit_post_path(@post) %></text>
<%= link_to "Delete Post", @post, method: :delete, data: { confirm: "Are you sure?" } %>
<%end%><br><br><br>
</div>
</div>